// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "goDDD/domain"

	mock "github.com/stretchr/testify/mock"
)

// FoodUsecase is an autogenerated mock type for the FoodUsecase type
type FoodUsecase struct {
	mock.Mock
}

// GetFood provides a mock function with given fields: ctx, food
func (_m *FoodUsecase) GetFood(ctx context.Context, food *domain.Food) (*domain.Food, error) {
	ret := _m.Called(ctx, food)

	var r0 *domain.Food
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Food) *domain.Food); ok {
		r0 = rf(ctx, food)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Food)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Food) error); ok {
		r1 = rf(ctx, food)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFood provides a mock function with given fields: ctx, food
func (_m *FoodUsecase) NewFood(ctx context.Context, food *domain.Food) (*domain.Food, error) {
	ret := _m.Called(ctx, food)

	var r0 *domain.Food
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Food) *domain.Food); ok {
		r0 = rf(ctx, food)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Food)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Food) error); ok {
		r1 = rf(ctx, food)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFoodUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewFoodUsecase creates a new instance of FoodUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFoodUsecase(t mockConstructorTestingTNewFoodUsecase) *FoodUsecase {
	mock := &FoodUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
